import {
    addAddress,
    deleteAddress,
    deleteUser,
    forgotPassword,
    getAllUsers,
    getProfile,
    getSession,
    getUserById,
    listUsers,
    login,
    logout,
    refresh,
    checkEmailAvailability,
    register,
    resetPassword,
    validateResetToken,
    updateAddress,
    updateProfile,
    updateUserRole,
    updateUserStatus,
} from "./user/user.handlers.js";
import {
    addressValidation,
    forgotPasswordValidation,
    loginValidation,
    checkEmailValidation,
    registerValidation,
    resetPasswordValidation,
    updateProfileValidation,
} from "./user/user.validators.js";

export {
    registerValidation,
    loginValidation,
    checkEmailValidation,
    updateProfileValidation,
    addressValidation,
    forgotPasswordValidation,
    resetPasswordValidation,
};

export const userController = {
    getSession,
    register,
    checkEmailAvailability,
    login,
    logout,
    refresh,
    forgotPassword,
    resetPassword,
    validateResetToken,
    getProfile,
    updateProfile,
    addAddress,
    updateAddress,
    deleteAddress,
    getAllUsers,
    getUserById,
    deleteUser,
    listUsers,
    updateUserRole,
    updateUserStatus,
};
