import { Address } from '@/types';
import { AddressFormData } from './AddressModal.types';

export const REGIONS = [
    'Arica y Parinacota',
    'Tarapaca',
    'Antofagasta',
    'Atacama',
    'Coquimbo',
    'Valparaiso',
    'Metropolitana',
    "O'Higgins",
    'Maule',
    'Nuble',
    'Biobio',
    'Araucania',
    'Los Rios',
    'Los Lagos',
    'Aysen',
    'Magallanes',
];

export const COMUNAS_BY_REGION: Record<string, string[]> = {
    'Arica y Parinacota': ['Arica', 'Camarones', 'Putre', 'General Lagos'],
    Tarapaca: ['Iquique', 'Alto Hospicio', 'Pozo Almonte', 'Camina', 'Colchane', 'Huara', 'Pica'],
    Antofagasta: [
        'Antofagasta',
        'Mejillones',
        'Sierra Gorda',
        'Taltal',
        'Calama',
        'Ollague',
        'San Pedro de Atacama',
        'Tocopilla',
        'Maria Elena',
    ],
    Atacama: ['Copiapo', 'Caldera', 'Tierra Amarilla', 'Chanaral', 'Diego de Almagro', 'Vallenar', 'Alto del Carmen', 'Freirina', 'Huasco'],
    Coquimbo: [
        'La Serena',
        'Coquimbo',
        'Andacollo',
        'La Higuera',
        'Paiguano',
        'Vicuna',
        'Illapel',
        'Canela',
        'Los Vilos',
        'Salamanca',
        'Ovalle',
        'Combarbala',
        'Monte Patria',
        'Punitaqui',
        'Rio Hurtado',
    ],
    Valparaiso: [
        'Valparaiso',
        'Casablanca',
        'Concon',
        'Juan Fernandez',
        'Puchuncavi',
        'Quintero',
        'Vina del Mar',
        'Isla de Pascua',
        'Los Andes',
        'Calle Larga',
        'Rinconada',
        'San Esteban',
        'La Ligua',
        'Cabildo',
        'Papudo',
        'Petorca',
        'Zapallar',
        'Quillota',
        'Calera',
        'Hijuelas',
        'La Cruz',
        'Nogales',
        'San Antonio',
        'Algarrobo',
        'Cartagena',
        'El Quisco',
        'El Tabo',
        'Santo Domingo',
        'San Felipe',
        'Catemu',
        'Llaillay',
        'Panquehue',
        'Putaendo',
        'Santa Maria',
        'Quilpue',
        'Limache',
        'Olmue',
        'Villa Alemana',
    ],
    Metropolitana: [
        'Santiago',
        'Cerrillos',
        'Cerro Navia',
        'Conchali',
        'El Bosque',
        'Estacion Central',
        'Huechuraba',
        'Independencia',
        'La Cisterna',
        'La Florida',
        'La Granja',
        'La Pintana',
        'La Reina',
        'Las Condes',
        'Lo Barnechea',
        'Lo Espejo',
        'Lo Prado',
        'Macul',
        'Maipu',
        'Nunoa',
        'Pedro Aguirre Cerda',
        'Penalolen',
        'Providencia',
        'Pudahuel',
        'Quilicura',
        'Quinta Normal',
        'Recoleta',
        'Renca',
        'San Joaquin',
        'San Miguel',
        'San Ramon',
        'Vitacura',
        'Puente Alto',
        'Pirque',
        'San Jose de Maipo',
        'Colina',
        'Lampa',
        'Tiltil',
        'San Bernardo',
        'Buin',
        'Calera de Tango',
        'Paine',
        'Melipilla',
        'Alhue',
        'Curacavi',
        'Maria Pinto',
        'San Pedro',
        'Talagante',
        'El Monte',
        'Isla de Maipo',
        'Padre Hurtado',
        'Penaflor',
    ],
    "O'Higgins": [
        'Rancagua',
        'Codegua',
        'Coinco',
        'Coltauco',
        'Donihue',
        'Graneros',
        'Las Cabras',
        'Machali',
        'Malloa',
        'Mostazal',
        'Olivar',
        'Peumo',
        'Pichidegua',
        'Quinta de Tilcoco',
        'Rengo',
        'Requinoa',
        'San Vicente',
        'Pichilemu',
        'La Estrella',
        'Litueche',
        'Marchihue',
        'Navidad',
        'Paredones',
        'San Fernando',
        'Chepica',
        'Chimbarongo',
        'Lolol',
        'Nancagua',
        'Palmilla',
        'Peralillo',
        'Placilla',
        'Pumanque',
        'Santa Cruz',
    ],
    Maule: [
        'Talca',
        'Constitucion',
        'Curepto',
        'Empedrado',
        'Maule',
        'Pelarco',
        'Pencahue',
        'Rio Claro',
        'San Clemente',
        'San Rafael',
        'Cauquenes',
        'Chanco',
        'Pelluhue',
        'Curico',
        'Hualane',
        'Licanten',
        'Molina',
        'Rauco',
        'Romeral',
        'Sagrada Familia',
        'Teno',
        'Vichuquen',
        'Linares',
        'Colbun',
        'Longavi',
        'Parral',
        'Retiro',
        'San Javier',
        'Villa Alegre',
        'Yerbas Buenas',
    ],
    Nuble: [
        'Chillan',
        'Bulnes',
        'Cobquecura',
        'Coelemu',
        'Coihueco',
        'Chillan Viejo',
        'El Carmen',
        'Ninhue',
        'Niquen',
        'Pemuco',
        'Pinto',
        'Portezuelo',
        'Quillon',
        'Quirihue',
        'Ranquil',
        'San Carlos',
        'San Fabian',
        'San Ignacio',
        'San Nicolas',
        'Treguaco',
        'Yungay',
    ],
    Biobio: [
        'Concepcion',
        'Coronel',
        'Chiguayante',
        'Florida',
        'Hualqui',
        'Lota',
        'Penco',
        'San Pedro de la Paz',
        'Santa Juana',
        'Talcahuano',
        'Tome',
        'Hualpen',
        'Lebu',
        'Arauco',
        'Canete',
        'Contulmo',
        'Curanilahue',
        'Los Alamos',
        'Tirua',
        'Los Angeles',
        'Antuco',
        'Cabrero',
        'Laja',
        'Mulchen',
        'Nacimiento',
        'Negrete',
        'Quilaco',
        'Quilleco',
        'San Rosendo',
        'Santa Barbara',
        'Tucapel',
        'Yumbel',
        'Alto Biobio',
    ],
    Araucania: [
        'Temuco',
        'Carahue',
        'Cunco',
        'Curarrehue',
        'Freire',
        'Galvarino',
        'Gorbea',
        'Lautaro',
        'Loncoche',
        'Melipeuco',
        'Nueva Imperial',
        'Padre Las Casas',
        'Perquenco',
        'Pitrufquen',
        'Pucon',
        'Saavedra',
        'Teodoro Schmidt',
        'Tolten',
        'Vilcun',
        'Villarrica',
        'Cholchol',
        'Angol',
        'Collipulli',
        'Curacautin',
        'Ercilla',
        'Lonquimay',
        'Los Sauces',
        'Lumaco',
        'Puren',
        'Renaico',
        'Traiguen',
        'Victoria',
    ],
    'Los Rios': ['Valdivia', 'Corral', 'Lanco', 'Los Lagos', 'Mafil', 'Mariquina', 'Paillaco', 'Panguipulli', 'La Union', 'Futrono', 'Lago Ranco', 'Rio Bueno'],
    'Los Lagos': [
        'Puerto Montt',
        'Calbuco',
        'Cochamo',
        'Fresia',
        'Frutillar',
        'Los Muermos',
        'Llanquihue',
        'Maullin',
        'Puerto Varas',
        'Castro',
        'Ancud',
        'Chonchi',
        'Curaco de Velez',
        'Dalcahue',
        'Puqueldon',
        'Queilen',
        'Quellon',
        'Quemchi',
        'Quinchao',
        'Osorno',
        'Puerto Octay',
        'Purranque',
        'Puyehue',
        'Rio Negro',
        'San Juan de la Costa',
        'San Pablo',
        'Chaiten',
        'Futaleufu',
        'Hualaihue',
        'Palena',
    ],
    Aysen: ['Coyhaique', 'Lago Verde', 'Aysen', 'Cisnes', 'Guaitecas', 'Cochrane', "O'Higgins", 'Tortel', 'Chile Chico', 'Rio Ibanez'],
    Magallanes: [
        'Punta Arenas',
        'Laguna Blanca',
        'Rio Verde',
        'San Gregorio',
        'Cabo de Hornos',
        'Antartica',
        'Porvenir',
        'Primavera',
        'Timaukel',
        'Natales',
        'Torres del Paine',
    ],
};

export const getEmptyFormData = (): AddressFormData => ({
    country: 'Chile',
    firstName: '',
    lastName: '',
    rut: '',
    company: '',
    street: '',
    apartment: '',
    zipCode: '',
    comuna: '',
    region: '',
    phone: '',
    isDefault: false,
});

export const mapInitialAddressToFormData = (initialData: Address): AddressFormData => {
    const parts = initialData.name.split(' ');

    return {
        country: initialData.country,
        firstName: parts[0] || '',
        lastName: parts.slice(1).join(' ') || '',
        rut: initialData.rut || '',
        company: initialData.company || '',
        street: initialData.street,
        apartment: '',
        zipCode: initialData.zipCode || '',
        comuna: initialData.comuna,
        region: initialData.region,
        phone: initialData.phone,
        isDefault: initialData.isDefault,
    };
};

export const validateAddressForm = (formData: AddressFormData) => {
    const errors: Record<string, string> = {};

    if (!formData.firstName.trim()) errors.firstName = 'El nombre es requerido';
    if (!formData.lastName.trim()) errors.lastName = 'El apellido es requerido';
    if (!formData.rut.trim()) errors.rut = 'El RUT es requerido';
    if (!formData.street.trim()) errors.street = 'La direccion es requerida';
    if (!formData.region) errors.region = 'La region es requerida';
    if (!formData.comuna) errors.comuna = 'La comuna es requerida';
    if (!formData.phone.trim()) errors.phone = 'El telefono es requerido';

    return errors;
};

export const mapFormDataToAddress = (formData: AddressFormData): Partial<Address> => {
    return {
        country: formData.country,
        name: `${formData.firstName} ${formData.lastName}`.trim(),
        rut: formData.rut,
        street: `${formData.street}${formData.apartment ? `, ${formData.apartment}` : ''}`.trim(),
        comuna: formData.comuna,
        region: formData.region,
        zipCode: formData.zipCode,
        phone: formData.phone,
        company: formData.company.trim(),
        isDefault: formData.isDefault,
    };
};

export const getAvailableComunas = (region: string) => {
    return region ? COMUNAS_BY_REGION[region] || [] : [];
};
